[project]
name = "apngc"
version = "0.1.0"
description = "Quickly create tiny compressed animated APNG that look great"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.7",
    "pyinstaller>=6.10.0",
    "pyside6>=6.7.2",
    "tinify>=1.6.0",
]
